name: Initialize Repository
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  issues: write 
jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jayalfredprufrock/create-issues-action@v1.2.1
