name: Test Schedule
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo message
        run: echo "This is a test"
